version: "3.9"

services:
  web:
    build:
      context: .
      args:
        SECRET_KEY: ${SECRET_KEY}
    env_file: .env
    volumes:
      - ./:/opt/webapp
    ports:
      - "8300:${PORT}"
  postgres:
    environment:
      POSTGRES_PASSWORD: <postgres_pwd>
    volumes:
      - postgres-data-humanity:/var/lib/postgresql/data
    ports:
      - "7432:5432"
  redis:
    ports:
      - "8379:6379"

volumes:
  postgres-data-humanity:
