# Generated by Django 4.1.1 on 2022-09-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('deployed_address', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('abi', models.JSONField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
