# Generated by Django 3.2.15 on 2022-09-09 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celo_humanity', '0002_rename_abi_contract_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255)),
                ('method_or_memo', models.CharField(blank=True, max_length=255)),
                ('receipt_id', models.CharField(max_length=255, null=True)),
                ('receipt', models.TextField(null=True)),
                ('crypto_wallet_id', models.CharField(max_length=128, null=True)),
                ('counterpart_crypto_wallet_id', models.CharField(max_length=128, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='celo_humanity.contract')),
            ],
        ),
    ]
