# Generated by Django 3.2.15 on 2022-09-12 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_merge_20220912_2254'),
        ('celo_humanity', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='users.consumer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='counterpart_consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterpart_transactions', to='users.consumer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='counterpart_merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterpart_transactions', to='users.merchant'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='friendly_memo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='users.merchant'),
        ),
    ]
