# Generated by Django 3.2.15 on 2022-09-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celo_humanity', '0004_auto_20220912_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
