# Generated by Django 3.2.15 on 2022-10-06 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_phone_number'),
        ('celo_humanity', '0006_auto_20220920_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('dwolla_id', models.CharField(db_index=True, max_length=255)),
                ('bank_name', models.CharField(max_length=70, unique=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ACHTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(null=True)),
                ('ach_id', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending')], max_length=10)),
                ('type', models.CharField(blank=True, choices=[('Withdraw', 'Withdraw'), ('Deposit', 'Deposit')], max_length=255)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='celo_humanity.account')),
                ('consumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ach_transactions', to='users.consumer')),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ach_transactions', to='users.merchant')),
            ],
        ),
    ]
