# Generated by Django 3.2.15 on 2022-10-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celo_humanity', '0007_account_achtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achtransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], max_length=10),
        ),
    ]
