# Generated by Django 3.2.16 on 2022-10-11 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celo_humanity', '0009_auto_20221006_1601'),
        ('celo_humanity', '0009_auto_20221008_2043'),
    ]

    operations = [
    ]
