# Generated by Django 3.2.16 on 2022-12-27 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20221207_1801'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('celo_humanity', '0010_merge_0009_auto_20221006_1601_0009_auto_20221008_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Executed', 'Executed')], default='Pending', max_length=16)),
                ('type', models.CharField(choices=[('fund_negative', 'Fund Negative Wallet'), ('burn_from_negative', 'Burn From Negative Wallet'), ('mint_to_positive', 'Mint To Positive Wallet'), ('positive_to_user', 'Transfer Adjustment To User')], max_length=255)),
                ('documentation', models.CharField(blank=True, max_length=255)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('approved_time', models.DateTimeField(null=True)),
                ('executed_time', models.DateTimeField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('consumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_actions', to='users.consumer')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_actions', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_actions', to='users.merchant')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='celo_humanity.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceActionSignoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signoff_time', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signoffs', to='celo_humanity.complianceaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signoffs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='complianceactionsignoff',
            constraint=models.UniqueConstraint(fields=('action_id', 'user_id'), name='one signoff per user'),
        ),
    ]
