# Generated by Django 3.2.16 on 2023-01-10 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_bankaccount'),
        ('celo_humanity', '0011_auto_20221227_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='achtransaction',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ach_transactions', to='home.bankaccount'),
        ),
        migrations.AlterField(
            model_name='complianceaction',
            name='type',
            field=models.CharField(choices=[('fund_negative', 'Fund Negative Wallet'), ('revert_fund_negative', 'Revert Fund Negative Wallet'), ('burn_from_negative', 'Burn From Negative Wallet'), ('mint_to_positive', 'Mint To Positive Wallet'), ('revert_mint_to_positive', 'Revert Mint To Positive Wallet'), ('positive_to_user', 'Transfer Adjustment To User')], max_length=255),
        ),
    ]
