# Generated by Django 3.2.16 on 2023-01-24 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celo_humanity', '0012_auto_20230110_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='achtransaction',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='complianceaction',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='complianceactionsignoff',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-id']},
        ),
    ]
