# Generated by Django 3.2.16 on 2023-02-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celo_humanity', '0013_auto_20230124_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceaction',
            name='latest_error',
            field=models.TextField(null=True),
        ),
    ]
