# Generated by Django 3.2.18 on 2023-02-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celo_humanity', '0014_complianceaction_latest_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='events_in_receipt',
            field=models.JSONField(null=True),
        ),
    ]
