# Generated by Django 3.2.18 on 2023-02-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celo_humanity', '0015_transaction_events_in_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='admin_wallet_action',
            field=models.BooleanField(default=False),
        ),
    ]
