# Generated by Django 3.2.18 on 2023-02-22 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celo_humanity', '0017_auto_20230222_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='original_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_transactions', to='celo_humanity.transaction'),
        ),
    ]
