export const icons = {
  back: require("./arrow-left.png"),
  bullet: require("./bullet.png"),
  bug: require("./ladybug.png"),
  next: require("./arrow-next.png"),
  down: require("./chevron-down.png"),
  nextWhite: require("./arrow-next-white.png"),
  dot: require("./dot-active.png"),
  dotInactive: require("./dot-inactive.png"),
  forward: require("./chevron-forward.png"),
  close: require("./close.png"),
  upload: require("./upload.png"),
  map: require("./map.png"),
  mapActive: require("./map-active.png"),
  calendar: require("./calendar.png"),
  calendarActive: require("./calendar-active.png"),
  message: require("./message.png"),
  messageActive: require("./message-active.png"),
  money: require("./money.png"),
  moneyActive: require("./money-active.png"),
  file: require("./file.png"),
  fileActive: require("./file-active.png"),
  profile: require("./profile.png"),
  edit: require("./edit.png"),
  settings: require("./settings.png"),
  electricity: require("./electricity.png"),
  electricityMarker: require("./electricity-marker.png"),
  fuel: require("./fuel.png"),
  fuelMarker: require("./fuel-marker.png"),
  pumpOut: require("./pump-out.png"),
  pumpOutMarker: require("./pump-out-marker.png"),
  paperPlane: require("./paper-plane.png"),
  plus: require("./plus.png"),
  minus: require("./minus.png"),
  boatInMarina: require("./boat-in-marina.png"),
  boatSeasonal: require("./boat-seasonal.png"),
  boatBoater: require("./boat-boater.png"),
  marker: require("./marker.png"),
  search: require("./search.png"),
  starActive: require("./star-active.png"),
  starInactive: require("./star-inactive.png"),
  boat: require("./boat.png"),
  chevronBack: require("./chevron-back.png"),
  chevronNext: require("./chevron-forward.png"),
  catamaran: require("./catamaran.png"),
  bowrider: require("./bowrider.png"),
  checkmark: require("./checkmark.png"),
  plusSquare: require("./plus-square.png"),

}

export type IconTypes = keyof typeof icons
