require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


platform :ios, '12.0'

target 'humanity_cash_mobil_33300' do

 # Flexbox Layout Manager Used By React Native
#   pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
 # React Native
#  pod 'React', path: '../node_modules/react-native', subspecs: [
#     # Comment out any unneeded subspecs to reduce bundle size.
# #     'DevSupport',
# #     'RCTActionSheet',
# #     'RCTAnimation',
# #     'RCTBlob',
# #     'RCTCameraRoll',
# #     'RCTGeolocation',
# #     'RCTImage',
# #     'RCTNetwork',
# #     'RCTPushNotification',
# #     'RCTSettings',
# #     'RCTTest',
# #     'RCTText',
# #     'RCTVibration',
# #     'RCTWebSocket',
# #     'RCTLinkingIOS'
#   ]

  # Mapbox
#   pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'


 permissions_path = '../node_modules/react-native-permissions/ios'

 pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'humanity_cash_mobil_33300Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()


   pre_install do |installer|
       $RNMBGL.pre_install(installer)
   end

   post_install do |installer|
        $RNMBGL.post_install(installer)




        react_native_post_install(installer)

        installer.pods_project.targets.each do |target|
              target.build_configurations.each do |config|

                config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"

                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
              end

     end
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
