# Generated by Django 4.1.1 on 2022-09-09 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cello_humanity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='abi',
            new_name='metadata',
        ),
    ]
