# Generated by Django 3.2.5 on 2022-09-23 22:12

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='Key')),
                ('value', models.TextField(verbose_name='Value')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=base.models.config_upload_dir)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
