# Generated by Django 3.2.15 on 2022-09-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_dwollaevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwollaevent',
            name='timestamp',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dwollaevent',
            name='customerLink',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
