# Generated by Django 3.2.15 on 2022-10-27 15:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('celo_humanity', '0006_auto_20220920_1308'),
        ('home', '0007_auto_20220929_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='DwollaOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('customerLink', models.CharField(max_length=200, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'Pending'), (3, 'Completed'), (4, 'Cancelled')])),
                ('type', models.IntegerField(choices=[(1, 'Withdraw'), (2, 'Deposit')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('timestamp', models.DateTimeField()),
                ('source', models.JSONField(blank=True, null=True)),
                ('destination', models.JSONField(blank=True, null=True)),
                ('crypto_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dwolla_counterpart', to='celo_humanity.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
