# Generated by Django 3.2.16 on 2023-01-10 16:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatedSystemBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tokens_minted', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('tokens_burned', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DatedSystemBalanceBankBalances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('credits_pending', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('credits_settled', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('debits_pending', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('debits_settled', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('comments', models.TextField(blank=True, default='')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_balances', to='home.datedsystembalance')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dated_balances', to='home.bankaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
