# Generated by Django 3.2.16 on 2023-01-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_datedsystembalance_datedsystembalancebankbalances'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank_order',
            field=models.IntegerField(default=1),
        ),
    ]
