# Generated by Django 3.2.16 on 2023-01-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_bankaccount_bank_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datedsystembalancebankbalances',
            name='comments',
        ),
        migrations.AddField(
            model_name='datedsystembalance',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
