# Generated by Django 3.2.18 on 2023-02-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20230110_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dwollaevent',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
