# Generated by Django 3.2.18 on 2023-03-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_dwollaevent_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['created']},
        ),
    ]
