# Generated by Django 3.2.13 on 2022-04-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_verified_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userverificationcode',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
