# Generated by Django 3.2.13 on 2022-05-05 20:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220415_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile-pictures')),
                ('address_1', models.CharField(max_length=150)),
                ('address_2', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'consumer',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile-pictures')),
                ('address_1', models.CharField(max_length=150)),
                ('address_2', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=16)),
                ('background_picture', models.ImageField(blank=True, null=True, upload_to='background-pictures')),
                ('business_name', models.CharField(max_length=50)),
                ('business_story', models.CharField(blank=True, max_length=50, null=True)),
                ('type_of_business', models.CharField(max_length=50)),
                ('registered_business_name', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('owner_first_name', models.CharField(max_length=150)),
                ('owner_last_name', models.CharField(max_length=150)),
                ('owner_address_1', models.CharField(max_length=150)),
                ('owner_address_2', models.CharField(blank=True, max_length=150, null=True)),
                ('owner_city', models.CharField(max_length=100)),
                ('owner_state', models.CharField(max_length=2)),
                ('owner_zip_code', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'merchant',
            },
        ),
    ]
