# Generated by Django 3.2.13 on 2022-05-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220510_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_touch_id',
            field=models.BooleanField(default=False),
        ),
    ]
