# Generated by Django 3.2.13 on 2022-06-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220606_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='website',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
