# Generated by Django 3.2.13 on 2022-06-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merchant_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='industry',
            field=models.CharField(blank=True, choices=[('Arts & entertainment', 'Arts & entertainment'), ('Communication & education', 'Communication & education'), ('Food & drink', 'Food & drink'), ('Health & wellness', 'Health & wellness'), ('Lodging', 'Lodging'), ('Shopping', 'Shopping'), ('Services', 'Services')], max_length=50, null=True),
        ),
    ]
