# Generated by Django 3.2.13 on 2022-07-08 14:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220621_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
