# Generated by Django 3.2.14 on 2022-09-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_merchant_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Google ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_token',
            field=models.TextField(blank=True, null=True, verbose_name='Google Token'),
        ),
    ]
