# Generated by Django 3.2.14 on 2022-09-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_merchant_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(choices=[('BANK', 'Bank'), ('MANAGER', 'Program Manager')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('SUPERVISOR', 'Supervisor'), ('ADMIN', 'Admin'), ('SUPERADMIN', 'Super Admin')], max_length=10, null=True),
        ),
    ]
