# Generated by Django 3.2.15 on 2022-09-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_merchant_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crypto_wallet_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
