# Generated by Django 3.2.14 on 2022-09-12 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220908_1415'),
        ('users', '0015_auto_20220912_2028'),
    ]

    operations = [
    ]
