# Generated by Django 3.2.15 on 2022-09-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_crypto_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='crypto_wallet_id',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
