# Generated by Django 3.2.15 on 2022-09-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_crypto_wallet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='crypto_wallet_id',
        ),
        migrations.AddField(
            model_name='consumer',
            name='crypto_wallet_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='crypto_wallet_id',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
