# Generated by Django 3.2.15 on 2022-09-12 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_merge_0015_auto_20220908_1415_0015_auto_20220912_2028'),
        ('users', '0017_auto_20220912_2055'),
    ]

    operations = [
    ]
