# Generated by Django 3.2.15 on 2022-09-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_merge_20220912_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='crypto_wallet_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='crypto_wallet_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
