# Generated by Django 3.2.15 on 2022-09-29 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20220926_1950'),
        ('users', '0019_auto_20220928_1947'),
    ]

    operations = [
    ]
