# Generated by Django 3.2.15 on 2022-09-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_merge_0019_auto_20220926_1950_0019_auto_20220928_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='DwollaUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('date_joined', models.DateTimeField(null=True)),
                ('dwolla_id', models.CharField(blank=True, max_length=50, null=True)),
                ('crypto_wallet_id', models.CharField(blank=True, max_length=128, null=True)),
                ('account_type', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'dwolla_user',
                'managed': False,
            },
        ),
    ]
