# Generated by Django 3.2.15 on 2022-10-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='business_story',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
