# Generated by Django 3.2.15 on 2022-10-07 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('users', '0024_auto_20221006_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region'),
        ),
    ]
