# Generated by Django 3.2.15 on 2022-10-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20221010_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
