# Generated by Django 3.2.16 on 2022-10-11 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20221007_1830'),
        ('users', '0029_coupon_code'),
    ]

    operations = [
    ]
