# Generated by Django 3.2.16 on 2022-10-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='facebook',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='instagram',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='twitter',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
