# Generated by Django 3.2.16 on 2022-12-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20221012_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
