# Generated by Django 3.2.18 on 2023-02-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20230124_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='crypto_wallet_address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='crypto_wallet_address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
